// Code generated by entc, DO NOT EDIT.

package sms

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the sms type in the database.
	Label = "sms"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldDischargeTimestamp holds the string denoting the discharge_timestamp field in the database.
	FieldDischargeTimestamp = "discharge_timestamp"
	// FieldDeliveryState holds the string denoting the delivery_state field in the database.
	FieldDeliveryState = "delivery_state"

	// Table holds the table name of the sms in the database.
	Table = "sm_ss"
)

// Columns holds all SQL columns for sms fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNumber,
	FieldData,
	FieldText,
	FieldDischargeTimestamp,
	FieldDeliveryState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// DeliveryState defines the type for the "delivery_state" enum field.
type DeliveryState string

// DeliveryStateUNCONFIRMED is the default value of the DeliveryState enum.
const DefaultDeliveryState = DeliveryStateUNCONFIRMED

// DeliveryState values.
const (
	DeliveryStateRECEIVED    DeliveryState = "RECEIVED"
	DeliveryStateUNKNOWN     DeliveryState = "UNKNOWN"
	DeliveryStateUNCONFIRMED DeliveryState = "UNCONFIRMED"
)

func (ds DeliveryState) String() string {
	return string(ds)
}

// DeliveryStateValidator is a validator for the "delivery_state" field enum values. It is called by the builders before save.
func DeliveryStateValidator(ds DeliveryState) error {
	switch ds {
	case DeliveryStateRECEIVED, DeliveryStateUNKNOWN, DeliveryStateUNCONFIRMED:
		return nil
	default:
		return fmt.Errorf("sms: invalid enum value for delivery_state field: %q", ds)
	}
}
