// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SmSsColumns holds the columns for the "sm_ss" table.
	SmSsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "number", Type: field.TypeString},
		{Name: "data", Type: field.TypeBytes},
		{Name: "text", Type: field.TypeString},
		{Name: "discharge_timestamp", Type: field.TypeTime},
		{Name: "delivery_state", Type: field.TypeEnum, Enums: []string{"RECEIVED", "UNKNOWN", "UNCONFIRMED"}, Default: "UNCONFIRMED"},
	}
	// SmSsTable holds the schema information for the "sm_ss" table.
	SmSsTable = &schema.Table{
		Name:        "sm_ss",
		Columns:     SmSsColumns,
		PrimaryKey:  []*schema.Column{SmSsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SmSsTable,
	}
)

func init() {
}
