// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lixin9311/sms-bot/ent/schema"
	"github.com/lixin9311/sms-bot/ent/sms"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	smsMixin := schema.SMS{}.Mixin()
	smsMixinFields0 := smsMixin[0].Fields()
	_ = smsMixinFields0
	smsFields := schema.SMS{}.Fields()
	_ = smsFields
	// smsDescCreatedAt is the schema descriptor for created_at field.
	smsDescCreatedAt := smsMixinFields0[0].Descriptor()
	// sms.DefaultCreatedAt holds the default value on creation for the created_at field.
	sms.DefaultCreatedAt = smsDescCreatedAt.Default.(func() time.Time)
	// smsDescUpdatedAt is the schema descriptor for updated_at field.
	smsDescUpdatedAt := smsMixinFields0[1].Descriptor()
	// sms.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sms.DefaultUpdatedAt = smsDescUpdatedAt.Default.(func() time.Time)
	// sms.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sms.UpdateDefaultUpdatedAt = smsDescUpdatedAt.UpdateDefault.(func() time.Time)
}
