// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lixin9311/sms-bot/ent/predicate"
	"github.com/lixin9311/sms-bot/ent/sms"
)

// SMSUpdate is the builder for updating SMS entities.
type SMSUpdate struct {
	config
	hooks    []Hook
	mutation *SMSMutation
}

// Where appends a list predicates to the SMSUpdate builder.
func (su *SMSUpdate) Where(ps ...predicate.SMS) *SMSUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SMSUpdate) SetUpdatedAt(t time.Time) *SMSUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetDeliveryState sets the "delivery_state" field.
func (su *SMSUpdate) SetDeliveryState(ss sms.DeliveryState) *SMSUpdate {
	su.mutation.SetDeliveryState(ss)
	return su
}

// SetNillableDeliveryState sets the "delivery_state" field if the given value is not nil.
func (su *SMSUpdate) SetNillableDeliveryState(ss *sms.DeliveryState) *SMSUpdate {
	if ss != nil {
		su.SetDeliveryState(*ss)
	}
	return su
}

// Mutation returns the SMSMutation object of the builder.
func (su *SMSUpdate) Mutation() *SMSMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SMSUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	su.defaults()
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SMSMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SMSUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SMSUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SMSUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SMSUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := sms.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SMSUpdate) check() error {
	if v, ok := su.mutation.DeliveryState(); ok {
		if err := sms.DeliveryStateValidator(v); err != nil {
			return &ValidationError{Name: "delivery_state", err: fmt.Errorf("ent: validator failed for field \"delivery_state\": %w", err)}
		}
	}
	return nil
}

func (su *SMSUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sms.Table,
			Columns: sms.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sms.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sms.FieldUpdatedAt,
		})
	}
	if su.mutation.ModemIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: sms.FieldModemID,
		})
	}
	if value, ok := su.mutation.DeliveryState(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: sms.FieldDeliveryState,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sms.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SMSUpdateOne is the builder for updating a single SMS entity.
type SMSUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SMSMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SMSUpdateOne) SetUpdatedAt(t time.Time) *SMSUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetDeliveryState sets the "delivery_state" field.
func (suo *SMSUpdateOne) SetDeliveryState(ss sms.DeliveryState) *SMSUpdateOne {
	suo.mutation.SetDeliveryState(ss)
	return suo
}

// SetNillableDeliveryState sets the "delivery_state" field if the given value is not nil.
func (suo *SMSUpdateOne) SetNillableDeliveryState(ss *sms.DeliveryState) *SMSUpdateOne {
	if ss != nil {
		suo.SetDeliveryState(*ss)
	}
	return suo
}

// Mutation returns the SMSMutation object of the builder.
func (suo *SMSUpdateOne) Mutation() *SMSMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SMSUpdateOne) Select(field string, fields ...string) *SMSUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated SMS entity.
func (suo *SMSUpdateOne) Save(ctx context.Context) (*SMS, error) {
	var (
		err  error
		node *SMS
	)
	suo.defaults()
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SMSMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SMSUpdateOne) SaveX(ctx context.Context) *SMS {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SMSUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SMSUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SMSUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := sms.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SMSUpdateOne) check() error {
	if v, ok := suo.mutation.DeliveryState(); ok {
		if err := sms.DeliveryStateValidator(v); err != nil {
			return &ValidationError{Name: "delivery_state", err: fmt.Errorf("ent: validator failed for field \"delivery_state\": %w", err)}
		}
	}
	return nil
}

func (suo *SMSUpdateOne) sqlSave(ctx context.Context) (_node *SMS, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sms.Table,
			Columns: sms.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sms.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing SMS.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sms.FieldID)
		for _, f := range fields {
			if !sms.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sms.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sms.FieldUpdatedAt,
		})
	}
	if suo.mutation.ModemIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: sms.FieldModemID,
		})
	}
	if value, ok := suo.mutation.DeliveryState(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: sms.FieldDeliveryState,
		})
	}
	_node = &SMS{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sms.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
